### ISSUE TITLE
Sequencing run demultiplexing for Novaseq

### ISSUE THREAD

**Issue by MatthewMah** [DReichLab/waldo#110]
We will provide the Broad the sample name (a barcode currently handled externally) with p5 index and p7 index. 

<img width="345" alt="demultiplex" src="https://user-images.githubusercontent.com/7673282/202760385-447812d9-8b67-4f03-9bd0-66fe149b6f57.png">

**Comment by KimCallan** [comment]
We've moved over to NovaSeq X which no longer requires this I think. So this might be obsolete
