### ISSUE TITLE
adding a calendar pop up wherever we input a date

### ISSUE THREAD

**Issue by KimCallan** [DReichLab/waldo#14]
Zhaos DB had a little calendar pop up whenever you were in a field that required a date, and was set to default show the current date. then you just clicked it and it filled in the date in the correct format. this would be nice since it is easier and should stop mistypes.

**Comment by MatthewMah** [comment]
https://stackoverflow.com/questions/660929/how-do-you-change-the-default-widget-for-all-django-date-fields-in-a-modelform
