### ISSUE TITLE
Blob Plates

### ISSUE THREAD

**Issue by KimCallan** [DReichLab/waldo#41]
Bands, Crowds, and Mobs typically have multiple libraries made of the same sample and so to save on capture reagents, we pool these back together once they've been barcoded. So we need to be able to combine multiple Bands/Crowds/Mobs together into one Blob plate of these pools.

**Comment by JNWorkman** [comment]
We also add individual recapture libraries to these Blob plates

**Comment by MatthewMah** [comment]
Resolved in b7f485c145e03096f0c69f4d858074295fff4bc3 and 0e25b2c7986d62b91e0e8e22705646f336af1eb3
