### ISSUE TITLE
Unnamed Capture Plate that works like Crowds/Mobs/Bands

### ISSUE THREAD

**Issue by KimCallan** [DReichLab/waldo#42]
We might do plates where we take a bunch of samples that need to be recaptured and put them all on one plate to get them done. So we need to be able to do what we do for Crowds/Mobs/Bands, where we submit a file of a bunch of S-IDs and have them layout onto a Capture plate (TW or RW)

**Comment by MatthewMah** [comment]
The solution for #41 provides a spreadsheet upload feature that allows specifying libraries and controls with positions. Is that sufficient for this as well?

**Comment by KimCallan** [comment]
I believe the solution made for #41 works as well for this one.
