### ISSUE TITLE
Rotating duplicate extract plates, combining and unrotating at capture stage

### ISSUE THREAD

**Issue by JNWorkman** [DReichLab/waldo#69]

**Comment by JNWorkman** [comment]
Top priority for now. 

David wants to move our standard wetlab process to doing 2 replicates of every plate. We need to create 2 RE batches from each LY batch. One of the two REs needs to be rotated 180degrees, i.e. A1 becomes H12. The two plates need to be combined (with the same libraries and controls in each well location) for TW and RW.

**Comment by MatthewMah** [comment]
I recall a proposal for a naming convention for rotated batches with U (upside down?). 

If for example, there are:
BatchName.12_DS
BatchName.12U_DS
Creating a capture batch from either of these will grab both and unrotate BatchName.12U_DS.

**Comment by ghost** [comment]
Hi Matt,

Kim and Noah are off this week. What you described is the naming convention that I recall as well.

Best,
Rebecca

From: MatthewMah ***@***.***>
Reply-To: DReichLab/waldo ***@***.***>
Date: Monday, June 27, 2022 at 5:21 PM
To: DReichLab/waldo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [DReichLab/waldo] Rotating duplicate extract plates, combining and unrotating at capture stage (Issue #69)


I recall a proposal for a naming convention for rotated batches with U (upside down?).

If for example, there are:
BatchName.12_DS
BatchName.12U_DS
Creating a capture batch from either of these will grab both and unrotate BatchName.12U_DS.
