### ISSUE TITLE
Lysate batch states

### ISSUE THREAD

**Issue by MatthewMah** [DReichLab/waldo#9]
Add:
1. In Progress
2. Closed

**Comment by KimCallan** [comment]
also please add a STOP status

**Comment by MatthewMah** [comment]
@KimCallan please review this state list:
1. Stop - something went wrong and this plate will stop processing
2. Open - can make changes to what powders are associated with this batch
3. In Progress - the current "Lysates created" state, but not able to make extract batch
4. Closed - can create a corresponding extract batch, still editable like "In Progress"

**Comment by KimCallan** [comment]
those look good to me. as long as we can move a plate from STOP back to one of the other states (in case we change our mind and decide to go ahead with a plate, rare but can happen depending on why exactly we stopped it). and when we move to Closed then make it that we have to have a Date filled in for Aisling.
