### ISSUE TITLE
Issues with CollabIDs in the downloaded spreadsheets

### ISSUE THREAD

**Issue by KimCallan** [DReichLab/waldo#95]
I don't know if this is something that can be fixed in WALDO to solve our problem. The issue is that when we download a spreadsheet from WALDO, and then open it in Excel on our computers, if the Collab-ID is a string of numbers that looks like a date, then Excel changes it to a date. and then, if we try to fix it by changing the rules of the cell to think its a text string, the date gets changed to excels background code for that date. 

Heres an example: the Powder Batch Snow.3 has a sample that the Collab-ID says is 6-6. But when I download the spreadsheet, excel converts that to 6-Jun. and then when i try to convert it back, all the formatting options change it to excels background code of 44718 instead of 6-6. so if one is just looking at the spreadsheet, no one knows that this sample is 6-6, and instead thinks its 44718

**Comment by MatthewMah** [comment]
We can try quoting the collaborator ID field. 

If that doesn't work, we may need to switch to a spreadsheet format instead of using a text file, but that's a more difficult change.

**Comment by MatthewMah** [comment]
https://stackoverflow.com/questions/165042/stop-excel-from-automatically-converting-certain-text-values-to-dates
